import 'package:get/get.dart';

class Languages extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
        'pt_BR': {
          'actualLanguage': "Português",
          'user': 'Usuario',
          'name': 'Nome',
          'nickname': 'Apelido',
          'password': 'Senha',
          'posts': 'Postagens',
          'likes': 'Curtidas',
          'birthDate': 'Data de Nascimento',
          'followers': 'Seguidores',
          'following': 'Seguindo',
          'nullaccount': 'Não tem uma conta?',
          'register': 'Cadastre-se',
          'forgotpassword': 'Esqueceu sua senha?',
          'alreadyhaveaccount': 'Ja tem uma conta?',
          'recover': 'Recuperar',
          'profile': 'Perfil',
          'change': 'Alterar',
          'theme': 'Tema',
          'light': 'Claro',
          'dark': 'Escuro',
          'language': 'Idioma',
          'pt': 'Português',
          'en': 'Inglês',
          'es': 'Espanhol',
          'logout': 'Sair',
          'anygossip': 'Alguma fofoca?',
          'required': 'Campo Obrigatorio',
          'login': 'Entrar',
          'save': 'Salvar',
          'loginError': 'Erro ao fazer login',
          'validData': 'Insira dados validos'
        },
        'en_US': {
          'actualLanguage': "English",
          'user': 'User',
          'name': 'Name',
          'nickname': 'Nickname',
          'password': 'Password',
          'posts': 'Posts',
          'likes': 'Likes',
          'birthDate': 'Birth Date',
          'followers': 'Followers',
          'following': 'Following',
          'nullaccount': 'Dont have an account?',
          'register': 'Register',
          'forgotpassword': 'Forgot your password?',
          'alreadyhaveaccount': 'Already have an account?',
          'recover': 'Recover',
          'profile': 'Profile',
          'change': 'Change',
          'theme': 'Theme',
          'light': 'Light',
          'dark': 'Dark',
          'language': 'Language',
          'pt': 'Portuguese',
          'en': 'English',
          'es': 'Spanish',
          'logout': 'Logout',
          'anygossip': 'Any gossip?',
          'required': "Required Field",
          'login': "Login",
          'save': 'Save',
          'loginError': 'Error on: logging in',
          'validData': 'Enter valid data'
        },
        'es_ES': {
          'actualLanguage': "Espanõl",
          'user': 'Usuario',
          'name': 'Nombre',
          'nickname': 'Apodo',
          'password': 'Clave',
          'posts': 'Correos',
          'likes': 'Gustos',
          'birthDate': 'Fecha de Nacimiento',
          'followers': 'Seguidores',
          'following': 'Siguiendo',
          'nullaccount': '¿No tienes una cuenta?',
          'register': 'Registro',
          'forgotpassword': '¿Olvidaste tu contraseña?',
          'alreadyhaveaccount': '¿Ya tienes una cuenta?',
          'recover': 'Recuperar',
          'profile': 'Perfil',
          'change': 'Cambiar',
          'theme': 'Tema',
          'light': 'Claro',
          'dark': 'Oscuro',
          'language': 'Idioma',
          'pt': 'Portugués',
          'en': 'Inglés',
          'es': 'Español',
          'logout': 'Salir',
          'anygossip': '¿Ningun chisme?',
          'required': "Campo Obligatorio",
          'login': "Iniciar Sesión",
          'save': 'Guardar',
          'loginError': 'Error on: Iniciar Sesión',
          'validData': 'Introduce datos válidos'
        },
      };
}
